version: '2'
services:
  jhipstersampleapplicationnovi-app:
    image: jhipstersampleapplicationnovi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplicationnovi-mysql:3306/jhipstersampleapplicationnovi?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstersampleapplicationnovi-mysql:
    extends:
      file: mysql.yml
      service: jhipstersampleapplicationnovi-mysql
